### ISSUE TITLE
Comments: Docker - Calibre-web Container Setup with New Calibre Database

### ISSUE THREAD

**Issue by fictionbecomesfact** [fictionbecomesfact/fictionbecomesfact_comments#47]
Comments for [Docker - Calibre-web Container Setup with New Calibre Database](https://fictionbecomesfact.com/calibre-web-container)

**Comment by lucasHabkost** [comment]
Hi!

I've deployed the container per the instructions, but when i try to execute the calibre commands inside the container it gives an error:

# calibredb restore_database --really-do-it --with-library /books
bash: calibredb: command not found

I can see calibredb listed:

/app/calibre/bin# ls -alh
total 2.0M
drwxr-xr-x 2 1000 1000 4.0K Jun 17 00:37 .
drwxr-xr-x 8 root root 4.0K Jun 17 01:39 ..
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre-complete
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre-customize
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibredb
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre-debug
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre-parallel
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre_postinstall
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre-server
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 calibre-smtp
-rwxr-xr-x 1 1000 1000 728K Jun 17 00:37 cjpeg
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 ebook-convert
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 ebook-device
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 ebook-edit
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 ebook-meta
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 ebook-polish
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 ebook-viewer
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 fetch-ebook-metadata
-rwxr-xr-x 1 1000 1000 595K Jun 17 00:37 jpegtran
-rwxr-xr-x 1 1000 1000 253K Jun 17 00:37 JxrDecApp
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 lrf2lrs
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 lrfviewer
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 lrs2lrf
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 markdown-calibre
-rwxr-xr-x 1 1000 1000 100K Jun 17 00:37 optipng
-rwxr-xr-x 1 1000 1000  39K Jun 17 00:37 pdfinfo
-rwxr-xr-x 1 1000 1000  96K Jun 17 00:37 pdftohtml
-rwxr-xr-x 1 1000 1000  23K Jun 17 00:37 pdftoppm
-rwxr-xr-x 1 1000 1000 6.2K Jun 17 00:37 web2disk

Any ideas on what I can be doing wrong?

Thanks in advance for your attention!

**Comment by fictionbecomesfact** [comment]
@lucasHabkost 
Thanks for adding the `ls` output, this list looks the same as mine, including the permissions. So that should be okay.
Unfortunately I can't reproduce the problem. When I go to `/app/calibre/bin` in the container then I can run `calibredb` without error. Does the `calibredb` command also not work when you run the program without the parameters (ie: `restore_database --really-do-it --with-library /books`)?

Also make sure the `/books` mapping exists in the container (so `cd /books` should work in the container), but given the error message that probably is not the problem.

I also looked at the calibre-web issues but didn't find anything there, but I did come across the [suggestion](https://github.com/janeczku/calibre-web/pull/2420) to add a pre-created database, that would be useful.

**Comment by fictionbecomesfact** [comment]
Glad you were able to resolve the issue with the db. I'm running calibre-web on an HP microserver (x86-64), so there's a difference. The Rpi4 should get the `arm64` image with the (default) `latest` tag. Optionally, you can also use for example the `arm64v8-0.6.18` tag (pull command: `linuxserver/calibre-web:arm64v8-0.6.18`), but it shouldn't be necessary. 

The logs on the host might also be interesting to look at (`docker logs calibreweb`).

E-book conversion will indeed not work according to the documentation of linuxserver but [these comments](https://github.com/linuxserver/docker-calibre-web/issues/93#issuecomment-661272327) might help you further: I did a quick read and in summary you can install calibre in the container (`apt update && apt install calibre`), then edit the path in calibreweb and e-book conversion seems to work. But I would recommend reading the comments, there is a lot more information in it and several solutions are mentioned.

**Comment by lucasHabkost** [comment]
Hi. I've resolved this manually installing Calibre inside the container.

I'll pressure test this solution, as I'm curious to what will happen when I update the container, or re-deploy it etc.
